// <auto-generated />
// Generated from @icon-park/svg 1.4.2 (Apache-2.0).
// Run "npm install && npm run generate" from tools/iconpark to refresh this file.

using System.Windows.Media;

namespace Hechao.Launcher.Controls;

internal sealed record IconParkPart(
    Geometry Geometry,
    bool Fill,
    bool Stroke,
    double StrokeWidth,
    PenLineCap LineCap,
    PenLineJoin LineJoin);

internal static class IconParkGeometryRegistry
{
    private static readonly IReadOnlyDictionary<IconParkKind, IconParkPart[]> Icons =
        new Dictionary<IconParkKind, IconParkPart[]>
        {
        [IconParkKind.Announcement] =
        [
            Part("M 6 15 H 42 A 2 2 0 0 1 44 17 V 39 A 2 2 0 0 1 42 41 H 6 A 2 2 0 0 1 4 39 V 17 A 2 2 0 0 1 6 15 Z", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Flat, lineJoin: PenLineJoin.Round),
            Part("M24 7L16 15H32L24 7Z", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round),
            Part("M12 24H30", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round),
            Part("M12 32H20", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round)
        ],
        [IconParkKind.Box] =
        [
            Part("M 8 12 H 40 A 2 2 0 0 1 42 14 V 40 A 2 2 0 0 1 40 42 H 8 A 2 2 0 0 1 6 40 V 14 A 2 2 0 0 1 8 12 Z", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Flat, lineJoin: PenLineJoin.Round),
            Part("M17.9497 24.0083L29.9497 24.0083", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round),
            Part("M6 13L13 5H35L42 13", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round)
        ],
        [IconParkKind.Calendar] =
        [
            Part("M5 19H43V40C43 41.1046 42.1046 42 41 42H7C5.89543 42 5 41.1046 5 40V19Z", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Flat, lineJoin: PenLineJoin.Round),
            Part("M5 9C5 7.89543 5.89543 7 7 7H41C42.1046 7 43 7.89543 43 9V19H5V9Z", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Flat, lineJoin: PenLineJoin.Round),
            Part("M16 4V12", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round),
            Part("M32 4V12", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round),
            Part("M28 34H34", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round),
            Part("M14 34H20", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round),
            Part("M28 26H34", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round),
            Part("M14 26H20", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round)
        ],
        [IconParkKind.CheckOne] =
        [
            Part("M24 44C29.5228 44 34.5228 41.7614 38.1421 38.1421C41.7614 34.5228 44 29.5228 44 24C44 18.4772 41.7614 13.4772 38.1421 9.85786C34.5228 6.23858 29.5228 4 24 4C18.4772 4 13.4772 6.23858 9.85786 9.85786C6.23858 13.4772 4 18.4772 4 24C4 29.5228 6.23858 34.5228 9.85786 38.1421C13.4772 41.7614 18.4772 44 24 44Z", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Flat, lineJoin: PenLineJoin.Round),
            Part("M16 24L22 30L34 18", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round)
        ],
        [IconParkKind.Close] =
        [
            Part("M8 8L40 40", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round),
            Part("M8 40L40 8", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round)
        ],
        [IconParkKind.Code] =
        [
            Part("M16 13L4 25.4322L16 37", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round),
            Part("M32 13L44 25.4322L32 37", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round),
            Part("M28 4L21 44", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Miter)
        ],
        [IconParkKind.Delete] =
        [
            Part("M9 10V44H39V10H9Z", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Flat, lineJoin: PenLineJoin.Round),
            Part("M20 20V33", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round),
            Part("M28 20V33", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round),
            Part("M4 10H44", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round),
            Part("M16 10L19.289 4H28.7771L32 10H16Z", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Flat, lineJoin: PenLineJoin.Round)
        ],
        [IconParkKind.Down] =
        [
            Part("M36 18L24 30L12 18", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round)
        ],
        [IconParkKind.Download] =
        [
            Part("M6 24.0083V42H42V24", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round),
            Part("M33 23L24 32L15 23", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round),
            Part("M23.9917 6V32", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round)
        ],
        [IconParkKind.ExternalTransmission] =
        [
            Part("M30 25L42 25", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round),
            Part("M36 19L42 25L36 31", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round),
            Part("M21 6V26C21 32.7391 14.8348 39.5668 9 42", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round),
            Part("M42 14V9C42 7.34315 40.6569 6 39 6H9C7.34315 6 6 7.34315 6 9V39C6 40.6569 7.34315 42 9 42H39C40.6569 42 42 40.6569 42 39V35.5", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round)
        ],
        [IconParkKind.Folder] =
        [
            Part("M7 6C7 4.89543 7.89543 4 9 4H39C40.1046 4 41 4.89543 41 6V42C41 43.1046 40.1046 44 39 44H9C7.89543 44 7 43.1046 7 42V6Z", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round),
            Part("M16 29H20", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round),
            Part("M16 35H26", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round),
            Part("M8 5C8 5 11.7647 18 24 18C36.2353 18 40 5 40 5", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round),
            Part("M 20 18 A 4 4 0 1 0 28 18 A 4 4 0 1 0 20 18 Z", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round),
            Part("M15 4H9C7.89543 4 7 4.89543 7 6V12", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round),
            Part("M33 4H39C40.1046 4 41 4.89543 41 6V12", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round)
        ],
        [IconParkKind.FolderOpen] =
        [
            Part("M4 9V41L9 21H39.5V15C39.5 13.8954 38.6046 13 37.5 13H24L19 7H6C4.89543 7 4 7.89543 4 9Z", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round),
            Part("M40 41L44 21H8.8125L4 41H40Z", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round)
        ],
        [IconParkKind.FullScreen] =
        [
            Part("M33 6H42V15", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round),
            Part("M42 33V42H33", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round),
            Part("M15 42H6V33", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round),
            Part("M6 15V6H15", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round)
        ],
        [IconParkKind.Game] =
        [
            Part("M38.5121 9.5362C34.8466 6.10249 29.9188 4 24.5 4C13.1782 4 4 13.1782 4 24.5C4 35.8218 13.1782 45 24.5 45C30.1148 45 35.2024 42.7427 38.9048 39.0861L24 24L38.5121 9.5362Z", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Flat, lineJoin: PenLineJoin.Round),
            Part("M40 28C42.2091 28 44 26.2091 44 24C44 21.7909 42.2091 20 40 20C37.7909 20 36 21.7909 36 24C36 26.2091 37.7909 28 40 28Z", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Flat, lineJoin: PenLineJoin.Round),
            Part("M17 13V21", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round),
            Part("M13 17H21", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round)
        ],
        [IconParkKind.History] =
        [
            Part("M5.81836 6.72729V14H13.0911", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round),
            Part("M4 24C4 35.0457 12.9543 44 24 44V44C35.0457 44 44 35.0457 44 24C44 12.9543 35.0457 4 24 4C16.598 4 10.1351 8.02111 6.67677 13.9981", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round),
            Part("M24.005 12L24.0038 24.0088L32.4832 32.4882", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round)
        ],
        [IconParkKind.IdCard] =
        [
            Part("M42 8H6C4.89543 8 4 8.89543 4 10V38C4 39.1046 4.89543 40 6 40H42C43.1046 40 44 39.1046 44 38V10C44 8.89543 43.1046 8 42 8Z", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Flat, lineJoin: PenLineJoin.Round),
            Part("M36 16H28V24H36V16Z", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Flat, lineJoin: PenLineJoin.Round),
            Part("M12 32H36", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round),
            Part("M12 16H18", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round),
            Part("M12 24H18", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round)
        ],
        [IconParkKind.Install] =
        [
            Part("M41.4004 11.551L36.3332 5H11.6666L6.58398 11.551", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round),
            Part("M6 13C6 11.8954 6.89543 11 8 11H40C41.1046 11 42 11.8954 42 13V40C42 41.6569 40.6569 43 39 43H9C7.34315 43 6 41.6569 6 40V13Z", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Flat, lineJoin: PenLineJoin.Round),
            Part("M32 27L24 35L16 27", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round),
            Part("M23.9917 19V35", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round)
        ],
        [IconParkKind.Lock] =
        [
            Part("M 8 22 H 40 A 2 2 0 0 1 42 24 V 42 A 2 2 0 0 1 40 44 H 8 A 2 2 0 0 1 6 42 V 24 A 2 2 0 0 1 8 22 Z", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Flat, lineJoin: PenLineJoin.Round),
            Part("M14 22V14C14 8.47715 18.4772 4 24 4C29.5228 4 34 8.47715 34 14V22", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round),
            Part("M24 30V36", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round)
        ],
        [IconParkKind.Minus] =
        [
            Part("M10.5 24L38.5 24", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round)
        ],
        [IconParkKind.PlayOne] =
        [
            Part("M15 24V11.8756L25.5 17.9378L36 24L25.5 30.0622L15 36.1244V24Z", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Flat, lineJoin: PenLineJoin.Round)
        ],
        [IconParkKind.Refresh] =
        [
            Part("M42 8V24", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round),
            Part("M6 24L6 40", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round),
            Part("M42 24C42 14.0589 33.9411 6 24 6C18.9145 6 14.3216 8.10896 11.0481 11.5M6 24C6 33.9411 14.0589 42 24 42C28.8556 42 33.2622 40.0774 36.5 36.9519", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round)
        ],
        [IconParkKind.Remind] =
        [
            Part("M24 4C16.268 4 10 10.268 10 18V38H38V18C38 10.268 31.732 4 24 4Z", fill: false, stroke: false, strokeWidth: 0d, lineCap: PenLineCap.Flat, lineJoin: PenLineJoin.Miter),
            Part("M10 38V18C10 10.268 16.268 4 24 4C31.732 4 38 10.268 38 18V38M4 38H44", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round),
            Part("M24 44C26.7614 44 29 41.7614 29 39V38H19V39C19 41.7614 21.2386 44 24 44Z", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round)
        ],
        [IconParkKind.Repair] =
        [
            Part("M17 14L29 14", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round),
            Part("M23 28L23 15", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round),
            Part("M20.1429 42H8C6.89543 42 6 41.1046 6 40V7C6 5.89543 6.89543 5 8 5H40C41.1046 5 42 5.89543 42 7V16.7167", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round),
            Part("M27 38L37.5 23.5L42 27L31 42H27V38Z", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round)
        ],
        [IconParkKind.Right] =
        [
            Part("M19 12L31 24L19 36", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round)
        ],
        [IconParkKind.Server] =
        [
            Part("M44 4H4V20H44V4Z", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Flat, lineJoin: PenLineJoin.Round),
            Part("M44 28H4V44H44V28Z", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Flat, lineJoin: PenLineJoin.Round),
            Part("M13 10H11C10.4477 10 10 10.4477 10 11V13C10 13.5523 10.4477 14 11 14H13C13.5523 14 14 13.5523 14 13V11C14 10.4477 13.5523 10 13 10Z", fill: true, stroke: false, strokeWidth: 0d, lineCap: PenLineCap.Flat, lineJoin: PenLineJoin.Miter),
            Part("M13 34H11C10.4477 34 10 34.4477 10 35V37C10 37.5523 10.4477 38 11 38H13C13.5523 38 14 37.5523 14 37V35C14 34.4477 13.5523 34 13 34Z", fill: true, stroke: false, strokeWidth: 0d, lineCap: PenLineCap.Flat, lineJoin: PenLineJoin.Miter),
            Part("M21 10H19C18.4477 10 18 10.4477 18 11V13C18 13.5523 18.4477 14 19 14H21C21.5523 14 22 13.5523 22 13V11C22 10.4477 21.5523 10 21 10Z", fill: true, stroke: false, strokeWidth: 0d, lineCap: PenLineCap.Flat, lineJoin: PenLineJoin.Miter),
            Part("M21 34H19C18.4477 34 18 34.4477 18 35V37C18 37.5523 18.4477 38 19 38H21C21.5523 38 22 37.5523 22 37V35C22 34.4477 21.5523 34 21 34Z", fill: true, stroke: false, strokeWidth: 0d, lineCap: PenLineCap.Flat, lineJoin: PenLineJoin.Miter)
        ],
        [IconParkKind.SettingTwo] =
        [
            Part("M18.2838 43.1713C14.9327 42.1736 11.9498 40.3213 9.58787 37.867C10.469 36.8227 11 35.4734 11 34.0001C11 30.6864 8.31371 28.0001 5 28.0001C4.79955 28.0001 4.60139 28.01 4.40599 28.0292C4.13979 26.7277 4 25.3803 4 24.0001C4 21.9095 4.32077 19.8938 4.91579 17.9995C4.94381 17.9999 4.97188 18.0001 5 18.0001C8.31371 18.0001 11 15.3138 11 12.0001C11 11.0488 10.7786 10.1493 10.3846 9.35011C12.6975 7.1995 15.5205 5.59002 18.6521 4.72314C19.6444 6.66819 21.6667 8.00013 24 8.00013C26.3333 8.00013 28.3556 6.66819 29.3479 4.72314C32.4795 5.59002 35.3025 7.1995 37.6154 9.35011C37.2214 10.1493 37 11.0488 37 12.0001C37 15.3138 39.6863 18.0001 43 18.0001C43.0281 18.0001 43.0562 17.9999 43.0842 17.9995C43.6792 19.8938 44 21.9095 44 24.0001C44 25.3803 43.8602 26.7277 43.594 28.0292C43.3986 28.01 43.2005 28.0001 43 28.0001C39.6863 28.0001 37 30.6864 37 34.0001C37 35.4734 37.531 36.8227 38.4121 37.867C36.0502 40.3213 33.0673 42.1736 29.7162 43.1713C28.9428 40.752 26.676 39.0001 24 39.0001C21.324 39.0001 19.0572 40.752 18.2838 43.1713Z", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Flat, lineJoin: PenLineJoin.Round),
            Part("M24 31C27.866 31 31 27.866 31 24C31 20.134 27.866 17 24 17C20.134 17 17 20.134 17 24C17 27.866 20.134 31 24 31Z", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Flat, lineJoin: PenLineJoin.Round)
        ],
        [IconParkKind.Shield] =
        [
            Part("M6 8.25564L24.0086 3L42 8.25564V19.0337C42 30.3622 34.7502 40.4194 24.0026 44.0005C13.2521 40.4195 6 30.36 6 19.0287V8.25564Z", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Flat, lineJoin: PenLineJoin.Round)
        ],
        [IconParkKind.Tool] =
        [
            Part("M44 16C44 22.6274 38.6274 28 32 28C29.9733 28 28.0639 27.4975 26.3896 26.6104L9 44L4 39L21.3896 21.6104C20.5025 19.9361 20 18.0267 20 16C20 9.37258 25.3726 4 32 4C34.0267 4 35.9361 4.50245 37.6104 5.38959L30 13L35 18L42.6104 10.3896C43.4975 12.0639 44 13.9733 44 16Z", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round)
        ],
        [IconParkKind.Up] =
        [
            Part("M13 30L25 18L37 30", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round)
        ],
        [IconParkKind.User] =
        [
            Part("M 16 12 A 8 8 0 1 0 32 12 A 8 8 0 1 0 16 12 Z", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round),
            Part("M42 44C42 34.0589 33.9411 26 24 26C14.0589 26 6 34.0589 6 44", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round)
        ],
        [IconParkKind.VolumeNotice] =
        [
            Part("M24 6V42C17 42 11.7985 32.8391 11.7985 32.8391H6C4.89543 32.8391 4 31.9437 4 30.8391V17.0108C4 15.9062 4.89543 15.0108 6 15.0108H11.7985C11.7985 15.0108 17 6 24 6Z", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Flat, lineJoin: PenLineJoin.Round),
            Part("M32 15L32 15C32.6232 15.5565 33.1881 16.1797 33.6841 16.8588C35.1387 18.8504 36 21.3223 36 24C36 26.6545 35.1535 29.1067 33.7218 31.0893C33.2168 31.7885 32.6391 32.4293 32 33", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round),
            Part("M34.2359 41.1857C40.0836 37.6953 44 31.305 44 24C44 16.8085 40.2043 10.5035 34.507 6.97906", fill: false, stroke: true, strokeWidth: 4d, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Miter)
        ]
        };

    public static IReadOnlyList<IconParkPart> GetParts(IconParkKind kind) =>
        Icons.TryGetValue(kind, out var parts)
            ? parts
            : Array.Empty<IconParkPart>();

    private static IconParkPart Part(
        string data,
        bool fill,
        bool stroke,
        double strokeWidth,
        PenLineCap lineCap,
        PenLineJoin lineJoin)
    {
        var geometry = Geometry.Parse(data);
        geometry.Freeze();
        return new IconParkPart(geometry, fill, stroke, strokeWidth, lineCap, lineJoin);
    }
}
