<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Hechao.Modpack</AssemblyName>
    <RootNamespace>Hechao.Modpack</RootNamespace>
    <Version>0.1.0</Version>
  </PropertyGroup>

</Project>
